// SIGN UP
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";

//SIGN IN
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
export const SIGNIN_ERROR = "SIGNIN_ERROR";

// SIGN UP
export const SIGNIN = "SIGNIN";
export const SIGNUP = "SIGNUP";

//LOGOUT
export const LOGOUT = "LOGOUT";

export const SIGNSTATE_CHANGED = "SIGNSTATE_CHANGED";

//COMPANIES

export const GETCOMPANIES = "GETCOMPANIES";
export const ADDCOMPANY = "ADDCOMPANY";
